### ISSUE TITLE
Where do I dl the mod please?

### ISSUE THREAD

**Issue by Jesse-Jamez** [nazarovtr/justice#61]
HI. 
Where do I DL the Justic mod please?

tx

**Comment by nazarovtr** [comment]
Hi Jesse-Jamez,

Thanks for your interest. It is not ready yet for public testing. You may
see this looking at github issues. I think I need a month or two before I
will add it to Steam Workshop. I'll notify you then.

Best regards,
Timur Nazarov

**Comment by Jesse-Jamez** [comment]
Hi Timur.
Sorry....im new to Github.
Didn't even think I would get a reply.
Ok....cool.

Thank you
Kind regards
Evian

**Comment by nazarovtr** [comment]
@Jesse-Jamez first version is available now http://steamcommunity.com/sharedfiles/filedetails/?id=1311705001

**Comment by Jesse-Jamez** [comment]
H Timur.

Thank you.....I started my first session now.
killed enemies in Kore base...but how to capture it?
make it turn blue or is that not an option?
tx
Evian

**Comment by nazarovtr** [comment]
@Jesse-Jamez Right. This is not an option. You kill them, they will not be respawned next time you come there. The base is abandoned by the enemy and you can not capture it. This is purely guerrilla warfare. Come, kill, steal or destroy, run. Right now there is no actual point in running, but soon there will be counterattacks.

**Comment by nazarovtr** [comment]
@Jesse-Jamez added this task for clarity: https://github.com/nazarovtr/justice/issues/116

**Comment by Jesse-Jamez** [comment]
Thanks man.
Another question:
When one dies...u have to abort and go back to lobby.
No option to respawn.....only to load a save game.
Is that mechanic going to stay like that?

**Comment by nazarovtr** [comment]
That was a bug related to updating the mission from 1-8 to 1-30. Now it is
fixed.

**Comment by nazarovtr** [comment]
@Jesse-Jamez

**Comment by Jesse-Jamez** [comment]
Thanks....i will tell Graeme. The two of us play together....he got locked
out of his github account.

**Comment by nazarovtr** [comment]
@Jesse-Jamez https://github.com/nazarovtr/justice/issues/116 done and released.
