### ISSUE TITLE
Mission List System and Feedback Issues of anitstasi addressed ?

### ISSUE THREAD

**Issue by GraemeC123** [nazarovtr/justice#83]
Hello Timur. 
I was just curious to know whether there was any intent to add any kind of "mission list" system to Justice or some kind of system that allows you the ability to focus missions on specific towns?
Also I realise that you are going for a more hardcore experience than antistasi, but have you ever considered adding more feedback mechanisms. Like marking on the map what the active area is and the radiuses that need to be cleared for AI? 
There's little more annoying than capturing an area in antistasi where there's one infantry man left in a bush, driving to the next objective only for the base to be recaptured instantly and re-garrisoned.

**Comment by nazarovtr** [comment]
Hi GraemeC123,

Justice is on very early stage of it's development. There are no missions for now. And I am not sure there will be missions like ones in Antistasi.

And here you do not fight for the support of specific towns. Reputation is counted for the whole island.
You do not conquer anything either. You are just a small force of guerillas which does not become an army at any point. It is more about hit and run and sabotage. So you won't need to focus your missions on some specific territory.
You can kill 70% of base personnel and it will become abandoned, but you can not place your own garrison there.

Enemy respawns have annoyed me too in Antistasi. So here I have two different things against this.
First, you indeed can click on the map and put a "point of interest" - a circle inside of which nothing will be despawned.
Second, all enemies are counted in Justice. You can get a sniper rifle, shoot a couple of soldiers on a base and run. Next time you get there, there will be 2 enemies less. Same with enemy vehicles.

**Comment by GraemeC123** [comment]
Oh ok. Thank-you for the reply.  Just out of interest are their any plans
to implement Vcom AI or anything similar ?

**Comment by nazarovtr** [comment]
I plan to test the mission with different AI enhancement mods and point out "supported" ones. The player may then choose what to use or just play vanilla.

**Comment by nazarovtr** [comment]
@GraemeC123 first version is available now http://steamcommunity.com/sharedfiles/filedetails/?id=1311705001

**Comment by nazarovtr** [comment]
And AI mods work fine.
